fetch_telematic_data:
  name: Fetch Telematic Data
  description: Fetch telematic data for a VIN using the stored container and log the response.
  fields:
    entry_id:
      description: Optional config entry id to target. Required if multiple entries are configured.
      example: 01K65NKFESKBQZ78PBW6V9BCCX
    vin:
      description: Optional VIN to query. Defaults to the first VIN seen on the stream.
      example: WBY31AW090FP15359
fetch_vehicle_mappings:
  name: Fetch Vehicle Mappings
  description: Fetch mapping information for the configured account and log the response.
  fields:
    entry_id:
      description: Optional config entry id to target. Required if multiple entries are configured.
      example: 01K65NKFESKBQZ78PBW6V9BCCX
fetch_basic_data:
  name: Fetch Basic Vehicle Data
  description: Fetch static vehicle metadata (model name, series, etc.) for a VIN and log the response.
  fields:
    entry_id:
      description: Optional config entry id to target. Required if multiple entries are configured.
      example: 01K65NKFESKBQZ78PBW6V9BCCX
    vin:
      description: Optional VIN to query. Defaults to the VIN stored in the config entry.
      example: WBY31AW090FP15359
